stages:
  - build
  - test

build-service:
  stage: build
  image: rust:latest
  variables:
    CARGO_HOME: /usr/local/cargo
  before_script:
    - cd service
    - rustup update
    - rustup component add clippy
    - rustc --version
    - cargo --version
  script:
    - cargo check
    - cargo clippy
    - cargo test
    - cargo build
  cache:
    paths:
    - target/
    - $CARGO_HOME
  