stages:
  - build
  - docker
  - e2e
  - deploy

build-service:
  stage: build
  image: adoptopenjdk/openjdk12:latest

  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

  before_script:
    - useradd -d /builds/{GITLAB_USER} -g users -M -N builder
    - chown -R builder:users ..

  script:
    - cd service
    - su -p -c "./mvnw $MAVEN_CLI_OPTS clean install" builder

  artifacts:
    paths:
      - service/target/goworlds-service.jar

  cache:
    key: goworlds-service
    paths:
      - $CI_PROJECT_DIR/.m2/repository

build-webapp:
  stage: build
  image: node:latest

  before_script:
    - cd webapp
    - yarn install

  script:
    - yarn test
    - yarn build

  artifacts:
    paths:
      - webapp/build

  cache:
    key: goworlds-webapp
    paths:
      - webapp/node_modules

build-service-container:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY/sazzer/goworlds/goworlds-service

  dependencies:
    - build-service

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd service
    - docker build -t $IMAGE_TAG:latest --build-arg JAR_FILE=target/goworlds-service.jar .
  after_script:
    - docker push $IMAGE_TAG:latest

build-webapp-container:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY/sazzer/goworlds/goworlds-webapp

  dependencies:
    - build-webapp

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd webapp
    - docker build -t $IMAGE_TAG:latest .
  after_script:
    - docker push $IMAGE_TAG:latest

build-e2e-container:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY/sazzer/goworlds/goworlds-e2e

  dependencies:
    - build-webapp

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd e2e
    - docker build -t $IMAGE_TAG:latest .
  after_script:
    - docker push $IMAGE_TAG:latest

run-e2e-tests:
  stage: e2e
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

  dependencies: []

  before_script:
    # Install Docker Compose
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base libffi-dev openssl-dev
    - pip install docker-compose

    # Grab the Docker Images to work with
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY/sazzer/goworlds/goworlds-service:latest
    - docker pull $CI_REGISTRY/sazzer/goworlds/goworlds-webapp:latest
    - docker pull $CI_REGISTRY/sazzer/goworlds/goworlds-e2e:latest
    - docker tag $CI_REGISTRY/sazzer/goworlds/goworlds-service:latest uk.co.grahamcox.goworlds/goworlds-service:latest
    - docker tag $CI_REGISTRY/sazzer/goworlds/goworlds-webapp:latest uk.co.grahamcox.goworlds/goworlds-webapp:latest
    - docker tag $CI_REGISTRY/sazzer/goworlds/goworlds-e2e:latest uk.co.grahamcox.goworlds/goworlds-e2e:latest

  script:
    - cd e2e
    - mkdir -p output
    - docker-compose up --abort-on-container-exit --exit-code-from goworlds-e2e

  artifacts:
    name: e2e-outputs
    when: always
    paths:
      - e2e/output

deploy-webapp:
  stage: deploy
  image: node:alpine

  variables:
    API_URI: https://goworlds-cd.herokuapp.com
    API_CLIENTID: 46F02F12-C566-4A23-BE53-801D3313C3A8

  before_script:
    - npm install -g netlify-cli
    - apk add gettext libintl
  script:
    - envsubst < webapp/build/config.js.template > webapp/build/config.js
    - |-
      netlify deploy --dir=webapp/build --message="GitLab job $CI_JOB_ID: $CI_COMMIT_SHORT_SHA" --prod

deploy-service:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

  before_script:
    - docker pull $CI_REGISTRY/sazzer/goworlds/goworlds-service:latest
    - apk add --no-cache curl
  script:
    - docker login --username=graham@grahamcox.co.uk --password=$HEROKU_API_KEY registry.heroku.com
    - docker tag $CI_REGISTRY/sazzer/goworlds/goworlds-service:latest registry.heroku.com/goworlds-cd/web
    - docker push registry.heroku.com/goworlds-cd/web
    - docker inspect registry.heroku.com/goworlds-cd/web:latest --format={{.Id}} > /tmp/imageid
    - |-
      curl -X PATCH https://api.heroku.com/apps/goworlds-cd/formation --header "Content-Type: application/json" --header "Accept: application/vnd.heroku+json; version=3.docker-releases" --user graham@grahamcox.co.uk:${HEROKU_API_KEY} --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat /tmp/imageid)'" } ] }'
