stages:
  - build
  - test

build-service:
  stage: build
  image: rust:latest
  before_script:
    - cd service
    - rustup update
    - rustup component add clippy
    - rustc --version
    - cargo --version
  script:
    - cargo check
    - cargo clippy
    - cargo test
    - cargo build
  cache:
    paths:
    - target/
  
build-service-container:
  stage: build
  before_script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/uk.co.grahamcox.goworlds/goworlds-service:latest service
  after_script:
    - docker push $CI_REGISTRY/uk.co.grahamcox.goworlds/goworlds-service:latest
