stages:
  - build
  - test

build-service:
  stage: build
  image: rust:latest
  before_script:
    - cd service
    - rustup update
    - rustup component add clippy
    - rustc --version
    - cargo --version
  script:
    - cd service
    - cargo check
    - cargo clippy
    - cargo test
    - cargo build