stages:
  - build
  - docker
  - e2e

build-service:
  stage: build
  image: adoptopenjdk/openjdk12:latest

  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

  before_script:
    - useradd -d /builds/{GITLAB_USER} -g users -M -N builder
    - chown -R builder:users ..

  script:
    - cd service
    - su -p -c "./mvnw $MAVEN_CLI_OPTS clean install" builder

  artifacts:
    paths:
      - service/target/goworlds-service.jar

  cache:
    key: goworlds-service
    paths:
      - $CI_PROJECT_DIR/.m2/repository

build-webapp:
  stage: build
  image: node:latest

  before_script:
    - cd webapp
    - yarn install

  script:
    - yarn test
    - yarn build

  artifacts:
    paths:
      - webapp/build

  cache:
    key: goworlds-webapp
    paths:
      - webapp/node_modules

build-service-container:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY/sazzer/goworlds/goworlds-service

  dependencies:
    - build-service

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd service
    - docker build -t $IMAGE_TAG:latest --build-arg JAR_FILE=target/goworlds-service.jar .
  after_script:
    - docker push $IMAGE_TAG:latest

build-webapp-container:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY/sazzer/goworlds/goworlds-webapp

  dependencies:
    - build-webapp

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd webapp
    - docker build -t $IMAGE_TAG:latest .
  after_script:
    - docker push $IMAGE_TAG:latest

run-e2e-tests:
  stage: e2e
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

  dependencies: []

  before_script:
    # Install Docker Compose
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base libffi-dev openssl-dev
    - pip install docker-compose

    # Grab the Docker Images to work with
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY/sazzer/goworlds/goworlds-service:latest
    - docker pull $CI_REGISTRY/sazzer/goworlds/goworlds-webapp:latest
    - docker tag $CI_REGISTRY/sazzer/goworlds/goworlds-service:latest uk.co.grahamcox.goworlds/goworlds-service:latest
    - docker tag $CI_REGISTRY/sazzer/goworlds/goworlds-webapp:latest uk.co.grahamcox.goworlds/goworlds-webapp:latest

  script:
    - cd e2e
    - docker build -t uk.co.grahamcox.goworlds/goworlds-e2e:latest .
    - mkdir -p output
    - docker-compose up --abort-on-container-exit --exit-code-from goworlds-e2e

  artifacts:
    name: e2e-outputs
    when: always
    paths:
      - e2e/output
