version: '3'
services:
    goworlds-postgres:
        image: postgres:10.6-alpine
        environment:
            POSTGRES_DB: goworlds
            POSTGRES_USER: goworlds
            POSTGRES_PASSWORD: goworlds
        ports:
            - "127.0.0.1:35432:5432"
        networks:
            - goworlds-dev
    goworlds-pgweb:
        image: sosedoff/pgweb
        environment:
            DATABASE_URL: postgres://goworlds:goworlds@goworlds-postgres:5432/goworlds?sslmode=disable
        ports:
            - "127.0.0.1:38081:8081"
        depends_on:
            - goworlds-postgres
        networks:
            - goworlds-dev
    goworlds-service:
        image: uk.co.grahamcox.goworlds/goworlds-service:latest
        environment:
            PORT: 8080
            DATABASE_URI: jdbc:postgresql://goworlds-postgres:5432/goworlds?user=goworlds&password=goworlds
            DOCKERIZE_WAIT: -wait tcp://goworlds-postgres:5432
        ports:
            - "127.0.0.1:38080:8080"
        networks:
            - goworlds-dev
    goworlds-ui:
        image: uk.co.grahamcox.goworlds/goworlds-ui:latest
        environment:
            API_URI: http://localhost:38080
            API_CLIENTID: 46F02F12-C566-4A23-BE53-801D3313C3A8
        ports:
            - "127.0.0.1:38000:80"
        networks:
            - goworlds-dev
networks:
    goworlds-dev:


