version: '2'

output: 'prefixed'

tasks:
  run-e2e:
    deps: [docker]
    cmds:
      - task run-e2e-tests

  run-e2e-tests:
    cmds:
      - docker-compose -f docker-compose.e2e.yml down
      - docker-compose -f docker-compose.e2e.yml up --exit-code-from=goworlds-e2e

  docker:
    deps: [docker-service,docker-e2e]

  docker-service:
    dir: service
    cmds:
      - task docker

  docker-e2e:
    dir: e2e
    cmds:
      - yarn docker
