INSERT INTO users(user_id,
                  version,
                  created,
                  updated,
                  name,
                  email,
                  password)
VALUES ('0A8E90D9-D971-4017-B4D9-240CDBFE5300',
        '19B53CE5-2DC6-4DF1-85A2-6DDC6BD33C08',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'System User',
        '',
        '');

INSERT INTO oauth2_clients(client_id,
                           version,
                           created,
                           updated,
                           name,
                           client_secret,
                           owner_id,
                           redirect_uris,
                           response_types,
                           grant_types)
VALUES ('46F02F12-C566-4A23-BE53-801D3313C3A8',
        '3F1072FB-90C2-426F-970E-39C5D2054144',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'System OAuth2 Client',
        '',
        '0A8E90D9-D971-4017-B4D9-240CDBFE5300',
        '{}',
        '{}',
        '{"CLIENT_CREDENTIALS", "REFRESH_TOKEN", "EMAIL_PASSWORD_EXTENSION"}');
