[package]
name = "goworlds-service"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[dependencies]
dotenv = "0.10.1"
config = "0.9.3"
serde = "1.0.91"
actix-web = "1.0.0-beta.3"
